//! Per-arch vDSO blob — embedded via `.incbin`, indexed via `.dynsym`.
//!
//! The blob is a pre-built `linux-vdso.so.1` committed under `blobs/`,
//! regenerated by `make regenerate-vdso-blobs`.

use core::arch::global_asm;

use spin::Once;
use xmas_elf::{ElfFile, sections::SectionData, symbol_table::Entry};

unsafe extern "C" {
    static vdso_start: u8;
    static vdso_end: u8;
}

macro_rules! incbin_vdso {
    ($arch:expr) => {
        concat!(
            ".section .rodata.vdso\n",
            ".balign 4096\n",
            ".global vdso_start, vdso_end\n",
            "vdso_start:\n",
            ".incbin \"",
            env!("CARGO_MANIFEST_DIR"),
            "/src/vdso/blobs/vdso-",
            $arch,
            ".so\"\n",
            ".balign 4096\n",
            "vdso_end:\n",
            ".previous"
        )
    };
}

#[cfg(target_arch = "riscv64")]
global_asm!(incbin_vdso!("riscv64"));
#[cfg(target_arch = "loongarch64")]
global_asm!(incbin_vdso!("loongarch64"));

/// The embedded vDSO ELF blob.
pub fn bytes() -> &'static [u8] {
    let start = &raw const vdso_start as *const u8;
    let end = &raw const vdso_end as *const u8;
    let len = unsafe { end.offset_from(start) } as usize;
    unsafe { core::slice::from_raw_parts(start, len) }
}

/// Symbol offsets `install` needs — resolved once per boot.
#[derive(Clone, Copy)]
pub struct Offsets {
    pub rt_sigreturn: usize,
    pub data_addr_slot: usize,
}

static OFFSETS: Once<Offsets> = Once::new();

/// Parse the embedded ELF on first call and cache the offsets.
pub fn offsets() -> Offsets {
    *OFFSETS.call_once(|| {
        let elf = ElfFile::new(bytes()).expect("vDSO blob is not a valid ELF");
        let mut rt_sigreturn = None;
        let mut data_addr_slot = None;
        for section in elf.section_iter() {
            let SectionData::DynSymbolTable64(entries) = section
                .get_data(&elf)
                .expect("vDSO blob has malformed section data")
            else {
                continue;
            };
            for sym in entries {
                match sym.get_name(&elf) {
                    Ok("__vdso_rt_sigreturn") => rt_sigreturn = Some(sym.value() as usize),
                    Ok("VDSO_DATA_ADDR") => data_addr_slot = Some(sym.value() as usize),
                    _ => {}
                }
            }
        }
        Offsets {
            rt_sigreturn: rt_sigreturn.expect("vDSO blob missing __vdso_rt_sigreturn"),
            data_addr_slot: data_addr_slot.expect("vDSO blob missing VDSO_DATA_ADDR"),
        }
    })
}
